# Generated by Django 2.2.6 on 2019-10-17 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='user',
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.UserDetails'),
            preserve_default=False,
        ),
    ]
