# Generated by Django 2.2.6 on 2019-10-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191017_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='status',
            new_name='active_status',
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('order_deadline', models.DateTimeField()),
                ('order_budget', models.IntegerField()),
                ('order_status', models.BooleanField(default=False)),
                ('job_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Jobs')),
                ('order_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserDetails')),
            ],
        ),
    ]
